# Generated by Django 5.0.3 on 2024-04-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('materia', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20)),
                ('objetivos', models.TextField()),
            ],
        ),
    ]
