# Generated by Django 5.0.3 on 2024-04-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('materia', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('condicion', models.CharField(blank=True, max_length=100, null=True)),
                ('carrera', models.CharField(blank=True, max_length=100, null=True)),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('semestre', models.CharField(blank=True, max_length=100, null=True)),
                ('requisitos', models.CharField(blank=True, max_length=100, null=True)),
                ('cargaSemanal', models.CharField(blank=True, max_length=100, null=True)),
                ('cargaSemestral', models.CharField(blank=True, max_length=100, null=True)),
                ('fundamentacion', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('evaluacion', models.TextField(blank=True, null=True)),
                ('bibliografia', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
