# Generated by Django 5.0.3 on 2024-04-23 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='id_carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.carrera'),
        ),
    ]
